### ISSUE TITLE
Similarity with http://alias.sh/

### ISSUE THREAD

**Issue by Potherca** [dougborg/dpend#2]
Not really an issue, more a comment.

What you want to achieve seems similar to what http://alias.sh/ does.
Maybe they might also be interested in something like this?

**Comment by dougborg** [comment]
Hey, thanks for the link to the alias.sh project! I hadn't seen that before and it looks really useful. I'd say my goals for dpend are a bit different though. I see it more as a package manager, build tool, set of conventions for bash projects.
